# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test Python Versions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        py_ver: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.py_ver }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.py_ver }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: build
        run: |
          echo '{
            "config": {
              "working_dir": "D:/work",
              "perl": "D:/work/perl/bin",
              "mingw": "D:/work/mingw/bin",
              "ohos_sdk": "D:/work/ohos-sdk/${ohos_version}",
              "ohos_version": 17,
              "build_type": "release",
              "build_ohos_abi": "arm64-v8a",
              "build_qt_tag": "v5.15.17-lts-lgpl",
              "clone_depth": 1,
              "jobs": 4,
              "verbose": false
            }
          }' > configure.json.user
          python ./build-qt-ohos.py --init --use_github
          python ./build-qt-ohos.py --exe_stage all --use_github
